### ISSUE TITLE
[NPM error] 

### ISSUE THREAD

**Issue by OddDevelopment** [workclocks/partyhat#1]
```
Error:

/root/partyhat/src/node_modules/express-rate-limit/dist/index.cjs:206
    const prefixedKey = `${store.prefix ?? ""}${key}`;
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/partyhat/src/index.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by workclocks** [comment]
installation on GNU Linux 6.5.5 worked fine, i assume its because you are attempting to run as root.
please do not run the project as root and run as a local user instead.
